version: 2.1

orbs:
  node: circleci/node@5 

jobs:
  test-node:
    executor: node/default
    working_directory: ~/project/my_api_project 
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: yarn 
      - run:
          name: Run tests
          command: echo "No test specified in package.json" 

  deploy:
    docker:
      - image: cimg/base:stable 
    steps:
      - checkout  
      - run:
          name: Install dependencies
          command: yarn install  
      - run:
          name: Start API locally
          command: |
            nohup node index.js &  # Lance ton serveur en arrière-plan avec nohup
            sleep 10  # Laisse quelques secondes au serveur pour démarrer
            curl http://localhost:3000/external-data  # Vérifie que ton serveur fonctionne en envoyant une requête à ton API

workflows:
  version: 2
  build-and-test:
    jobs:
      - test-node 
      - deploy:  
          requires:
            - test-node  